name: Issue Webhook Notifier

on:
  issues:
    types: [opened]

jobs:
  notify-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send webhook request
        run: |
          WEBHOOK_URL="https://discord.com/api/webhooks/1337904272628514866/IKakRwrZvE470Hf0f1RVkeNB92NyAQk1PvNG_WRHD59W1nVlD7Wqt9g4OR7TibLdMGxG"
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"
          ISSUE_URL="${{ github.event.issue.html_url }}"
          PAYLOAD=$(jq -n \
            --arg title "$ISSUE_TITLE" \
            --arg body "$ISSUE_BODY" \
            --arg url "$ISSUE_URL" \
            '{title: $title, body: $body, url: $url}')
          
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            "$WEBHOOK_URL"
