name: Notify Discord on Bug Report

on:
  issues:
    types: [opened]

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Send bug report to Discord
        if: |
          contains(toJson(github.event.issue.labels.*.name), 'bug')
        run: |
          curl -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
          -H "Content-Type: application/json" \
          -d '{
                "content": "**New Bug Report Created!**",
                "embeds": [
                  {
                    "title": "${{ github.event.issue.title }}",
                    "description": "${{ github.event.issue.body }}",
                    "url": "${{ github.event.issue.html_url }}",
                    "fields": [
                      {
                        "name": "User",
                        "value": "${{ github.event.issue.user.login }}",
                        "inline": true
                      }
                    ]
                  }
                ]
              }'
